apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-config
  namespace: whisper
data:
  STREAM_MODEL: "phate334/Breeze-ASR-25-ct2"
  DEVICE: "cuda"
  COMPUTE_TYPE: "float16"
  MAX_CONNECTIONS: "10"
