apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: whisper
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: model-cache-pv
