apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: whisper
spec:
  selector:
    app: api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - port: 8000
      targetPort: 8000
